# Generated by Django 3.1.6 on 2021-03-07 06:36

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Appinfo',
            fields=[
                ('md5', models.CharField(max_length=30, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=250, verbose_name='应用名')),
                ('apk_file', models.FileField(upload_to='uploads/%Y/%m/%d/')),
                ('avater', models.FilePathField(verbose_name='/Users/nine/VSCode/python-project/django-Study/media/avater/default.png')),
                ('package_name', models.CharField(max_length=250, verbose_name='包名')),
                ('version_code', models.CharField(max_length=250, verbose_name='版本号')),
                ('version_name', models.CharField(max_length=250, verbose_name='版本名')),
                ('created', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ('-name',),
            },
        ),
    ]
