# Generated by Django 3.1.4 on 2021-03-09 11:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pretreat', '0002_auto_20210308_2158'),
    ]

    operations = [
        migrations.CreateModel(
            name='AppInfo',
            fields=[
                ('md5', models.CharField(max_length=30, primary_key=True, serialize=False)),
                ('apk_file', models.FileField(upload_to='uploads/%Y/%m/%d/')),
                ('name', models.CharField(max_length=250, verbose_name='应用名')),
                ('avater', models.FilePathField(verbose_name='E:\\JoJo-Test\\mysite\\media/avater/default.png')),
                ('package_name', models.CharField(max_length=250, verbose_name='包名')),
                ('version_code', models.CharField(max_length=250, verbose_name='版本号')),
                ('version_name', models.CharField(max_length=250, verbose_name='版本名')),
                ('created', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ('-created',),
            },
        ),
        migrations.RemoveField(
            model_name='appmoreinfo',
            name='app',
        ),
        migrations.DeleteModel(
            name='AppBaseInfo',
        ),
        migrations.DeleteModel(
            name='AppMoreinfo',
        ),
    ]
